---
- name: Day 4 - Variaveis
  hosts: all
  become: true
  
  # Isto é uma Playbook Variable (Global para este ficheiro)
  vars:
    pacote_web: nginx
    pasta_html: /var/www/html

  tasks:
    - name: Instalar servidor web (usando Playbook Variable)
      apt:
        name: "{{ pacote_web }}"
        state: present
        update_cache: yes

    - name: Iniciar servico
      service:
        name: "{{ pacote_web }}"
        state: started

    - name: Criar ficheiro com Facts do Sistema
      copy:
        content: |
          <h1>Este servidor e do tipo: {{ nome_servidor }}</h1>
          <h3>Detalhes Automaticos (Facts):</h3>
          <ul>
            <li>IP Address: {{ ansible_default_ipv4.address }}</li>
            <li>Sistema Operativo: {{ ansible_distribution }} {{ ansible_distribution_version }}</li>
            <li>CPU Cores: {{ ansible_processor_vcpus }}</li>
            <li>Memoria Livre: {{ ansible_memfree_mb }} MB</li>
          </ul>
        dest: "{{ pasta_html }}/index.html"
